#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-or-later.
# Copyright © 2017-2019 by The qTox Project Contributors
# Copyright © 2024 The TokTok team

set -eu -o pipefail

QTOX_DIR="$1"

BUNDLE_PATH="$(realpath "$2")"
BUILD_DIR="$(realpath "$BUNDLE_PATH/..")"

APP_VER=$(defaults read "$BUNDLE_PATH/Contents/Info.plist" CFBundleVersion)

if [ ! -d "$BUNDLE_PATH" ]; then
  echo "Please pass path to qTox.app as an argument!"
  exit 1
fi

rm -f "$BUILD_DIR/qTox.dmg"

create-dmg \
  --filesystem APFS \
  --no-internet-enable \
  --volname "qTox $APP_VER" \
  --volicon "$QTOX_DIR/img/icons/qtox.icns" \
  --background "$QTOX_DIR/macos/backgroundImage.tiff" \
  --eula "$QTOX_DIR/macos/gplv3.rtf" \
  --window-pos 200 120 \
  --window-size 640 480 \
  --icon-size 128 \
  --hide-extension "qTox.app" \
  --icon "qTox.app" 0 300 \
  --app-drop-link 400 300 \
  "$BUILD_DIR/qTox.dmg" \
  "$BUNDLE_PATH"
