#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-or-later.
# Copyright © 2017-2019 by The qTox Project Contributors
# Copyright © 2024 The TokTok team

set -eu -o pipefail

QTOX_DIR="$1"

cd "$2"
BUNDLE_PATH="$PWD"
cd -

cd "$BUNDLE_PATH/../"
BUILD_DIR="$PWD"
cd -

DMG_DIR="$BUILD_DIR/dmg.tmp"
APP_VER=$(defaults read "$BUNDLE_PATH/Contents/Info.plist" CFBundleVersion)

if [ ! -d "$BUNDLE_PATH" ]; then
  echo "Please pass path to qTox.app as an argument!"
  exit 1
fi

rm -rf "$DMG_DIR"
rm -f "$BUILD_DIR/qTox.dmg"
mkdir "$DMG_DIR"
cp -r "$BUNDLE_PATH" "$DMG_DIR/"

cd "$DMG_DIR"
ln -s /Applications "./Install to Applications"
mkdir .background
cp -f "$QTOX_DIR"/macos/background-DMG/qTox-DMG-bak.tiff .background/backgroundImage.tiff
cp -f "$QTOX_DIR"/macos/DS_Store-DMG ./.DS_Store
cp -f "$QTOX_DIR"/LICENSE ./LICENSE
cp -f "$QTOX_DIR"/README.md ./README.md
cd -

hdiutil create -volname "qTox $APP_VER" -srcfolder "$DMG_DIR/" -format UDZO "$BUILD_DIR/qTox.dmg"
