name: Package

on:
  # Run this workflow every day at 3:00 UTC to update caches.
  schedule: [cron: '0 3 * * *']
  # Allow manual trigger.
  workflow_dispatch:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
    tags: ["v*"]

# Cancel old PR builds when pushing new commits.
concurrency:
  group: build-package-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
   build-fedora-rpm:
     name: Build RPM package on Fedora
     runs-on: ubuntu-24.04
     steps:
       - uses: actions/checkout@v4
       - name: Cache compiler output
         uses: actions/cache@v4
         with:
           path: ".cache/ccache"
           key: ${{ github.job }}-ccache
       - name: Build package
         run: docker compose run --rm fedora .ci-scripts/package-qtox-linux.sh --source-dir . --target-dir build_dir
